#syntax=ghcr.io/aica-technology/package-builder:v1.1.1

[signing]
enabled = false
signer = "v2.0.2"

[metadata]
version = "0.0.1"
description = "xArm collection"

[metadata.collection]
name = "collections/xarm-collection"
ros-name = "collections_xarm_collection"

[build]
type = "ros"
image = "v2.0.0-jazzy"

[build.packages.description]
source = "xarm_description"
